### ISSUE TITLE
:symbolize_keys parser option does not work properly for Array of Tables

### ISSUE THREAD

**Issue by amon-sha** [emancu/toml-rb#104]
There is a way to define [Arrays of Tables]( https://github.com/toml-lang/toml#array-of-tables) in TOML
The :symbolize_keys parser option works for tables inside the array, but not for the outer key.
Parsing the example from TOML readme produces:
```ruby
{"products"=>
  [{:name=>"Hammer", :sku=>738594937}, {}, {:name=>"Nail", :sku=>284758393, :color=>"gray"}]}
```
while the expected result is:
```ruby
{:products=>
  [{:name=>"Hammer", :sku=>738594937}, {}, {:name=>"Nail", :sku=>284758393, :color=>"gray"}]}
```

**Comment by emancu** [comment]
Thanks for reporting this issue.
I am a little busy this week, but I will take a look next week for sure!
