### ISSUE TITLE
`require_relative` not available prior to Ruby 1.9

### ISSUE THREAD

**Issue by sparr** [emancu/toml-rb#109]
Either the gem manifest should require Ruby 1.9+ or the uses of `require_relative "blah"` should be replaced with the longer `require File.join(File.dirname(__FILE__), 'blah')` or perhaps some third option?

**Comment by sparr** [comment]
Drat. I had hoped for the 1.8-compatible solution. Thanks for the quick fix, at least!

**Comment by emancu** [comment]
@sparr ^^ I remember having issues with older versions, that's why I run tests only for 2.2+

Also 1.8.7 was deprecated long time ago. However if you want to send a PR I'm open to accept it, as long as the tests passes in all the supported versions!
