### ISSUE TITLE
Dumping a regex results in invalid output

### ISSUE THREAD

**Issue by philomory** [emancu/toml-rb#118]
```
irb(main):001:0> example = { 'foo' => { 'bar' => /ba*z/ } }
=> {"foo"=>{"bar"=>/ba*z/}}
irb(main):002:0> puts TomlRB.dump(example)
[foo]
bar = /ba*z/
=> nil
```

When a hash containing a regular expression is dumped as TOML, the resulting output isn't syntactically valid TOML. Of course, there doesn't exist any TOML type for regular expressions; they are commonly represented as strings.

Preferred solution:
Convert the regular expression to a string (by calling `Regexp#source`) when dumping:
```
irb(main):003:0> example = { 'foo' => { 'bar' => /ba*z/ } }
=> {"foo"=>{"bar"=>/ba*z/}}
irb(main):004:0> puts TomlRB.dump(example)
[foo]
bar = "ba*z"
=> nil
```

Sort-of acceptable alternative:
Raise an exception when trying to dump a regular expression:
```
irb(main):005:0> example = { 'foo' => { 'bar' => /ba*z/ } }
=> {"foo"=>{"bar"=>/ba*z/}}
irb(main):006:0> puts TomlRB.dump(example)
TomlRB::InvalidObjectException: Object of class Regexp cannot be dumped to TOML.
  from (irb):6
```

**Comment by emancu** [comment]
@philomory Thanks for the issue reported.

Taken from docs: 

> If you're a frequent specifier of Windows paths or regular expressions, then having to escape backslashes quickly becomes tedious and error-prone. To help, TOML supports literal strings which do not allow escaping at all.

So the solution will raise an error :/ to keep the gem aligned to the specs.

**Comment by philomory** [comment]
I'm not sure how that follows?

**Comment by emancu** [comment]
@philomory sorry that took me too much to address this issue. Actually other contributor did it with a PR.

I am releasing the new version of the gem in a few minutes, hope it helps you
