### ISSUE TITLE
Support quoted keys

### ISSUE THREAD

**Issue by rsim** [emancu/toml-rb#31]
From TOML 0.3.1 specification:

Keys may be either bare or quoted. Bare keys may only contain letters, numbers, underscores, and dashes (A-Za-z0-9_-). Quoted keys follow the exact same rules as basic strings and allow you to use a much broader set of key names. Best practice is to use bare keys except when absolutely necessary.
```toml
"127.0.0.1" = "value"
"character encoding" = "value"
"ʎǝʞ" = "value"
```
Dots are prohibited in bare keys because dots are used to signify nested tables! Naming rules for each dot separated part are the same as for keys (see above).
```toml
[dog."tater.man"]
type = "pug"
```
In JSON land, that would give you the following structure:
```json
{ "dog": { "tater.man": { "type": "pug" } } }
```
Whitespace around dot-separated parts is ignored, however, best practice is to not use any extraneous whitespace.
```toml
[a.b.c]          # this is best practice
[ d.e.f ]        # same as [d.e.f]
[ g .  h  . i ]  # same as [g.h.i]
[ j . "ʞ" . l ]  # same as [j."ʞ".l]
```

**Comment by emancu** [comment]
@rsim @mojombo what about the bare keys with `?` or `#` chars? 
We want to still support them ? I can see the `hard_example` file use that kind of keys.

**Comment by rsim** [comment]
@emancu According to the latest specification bare keys may only contain letters, numbers, underscores, and dashes (A-Za-z0-9_-). So `hard_example` file should be modified and keys with `?` and `#` should be quoted.

**Comment by emancu** [comment]
@rsim thanks !

BTW the [example file](https://github.com/toml-lang/toml/blob/master/examples/example-v0.3.0.toml) should show some examples of quoted keys.
