### ISSUE TITLE
parse failed for multi-line array with commented elements

### ISSUE THREAD

**Issue by rsim** [emancu/toml-rb#38]
The latest version from master branch fails to parse multi-line array where some values are commented out:
```
>> TOML.parse <<-EOS
a = [
1,
# 2,
# 3
]
EOS
TOML::ParseError: Failed to parse input on line 3 at offset 5
# 2,

     ^
	from /Users/raymond/.rvm/gems/ruby-2.1.1@toml/bundler/gems/toml-rb-1d91dc3d1c76/lib/toml/parser.rb:16:in `rescue in initialize'
	from /Users/raymond/.rvm/gems/ruby-2.1.1@toml/bundler/gems/toml-rb-1d91dc3d1c76/lib/toml/parser.rb:12:in `initialize'
	from /Users/raymond/.rvm/gems/ruby-2.1.1@toml/bundler/gems/toml-rb-1d91dc3d1c76/lib/toml.rb:30:in `new'
	from /Users/raymond/.rvm/gems/ruby-2.1.1@toml/bundler/gems/toml-rb-1d91dc3d1c76/lib/toml.rb:30:in `parse'
```

**Comment by emancu** [comment]
Thanks for report the issue.
I'll take a look later.

On Tuesday, January 27, 2015, Raimonds Simanovskis <notifications@github.com>
wrote:

> The latest version from master branch fails to parse multi-line array
> where some values are commented out:
>
> >> TOML.parse <<-EOS
> a = [
> 1,
> # 2,
> # 3
> ]
> EOS
> TOML::ParseError: Failed to parse input on line 3 at offset 5
> # 2,
>
>      ^
>     from /Users/raymond/.rvm/gems/ruby-2.1.1@toml/bundler/gems/toml-rb-1d91dc3d1c76/lib/toml/parser.rb:16:in `rescue in initialize'
>     from /Users/raymond/.rvm/gems/ruby-2.1.1@toml/bundler/gems/toml-rb-1d91dc3d1c76/lib/toml/parser.rb:12:in `initialize'
>     from /Users/raymond/.rvm/gems/ruby-2.1.1@toml/bundler/gems/toml-rb-1d91dc3d1c76/lib/toml.rb:30:in `new'
>     from /Users/raymond/.rvm/gems/ruby-2.1.1@toml/bundler/gems/toml-rb-1d91dc3d1c76/lib/toml.rb:30:in `parse'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emancu/toml-rb/issues/38>.
>


-- 
Emiliano Mancuso <http://about.me/emancu>
