### ISSUE TITLE
circular argument reference - pos

### ISSUE THREAD

**Issue by bararchy** [emancu/toml-rb#45]
This is happening for a while now, I know this is an issue with 'citrus' gem but maybe this is an error from toml-rb usage of the citrus gem ? 

```
[3] pry(main)> require 'toml'
/home/user/.rvm/gems/ruby-head/gems/citrus-3.0.1/lib/citrus.rb:202: warning: circular argument reference - pos
/home/user/.rvm/gems/ruby-head/gems/citrus-3.0.1/lib/citrus.rb:214: warning: circular argument reference - pos
/home/user/.rvm/gems/ruby-head/gems/citrus-3.0.1/lib/citrus.rb:226: warning: circular argument reference - pos
/home/user/.rvm/gems/ruby-head/gems/citrus-3.0.1/lib/citrus.rb:234: warning: circular argument reference - pos
```

**Comment by emancu** [comment]
I already submit a [PR](https://github.com/mjackson/citrus/pull/49) on `citrus` and it was merged.
They have to release a new version of the gem, there is nothing else that I can do from `toml-rb`.

@blambeau could you please release a new version of `citrus`?
Thanks!

**Comment by blambeau** [comment]
@emancu Unfortunately I can't cut a release myself. I've opened an issue there.
