### ISSUE TITLE
Cannot parse multi-line array with comment lines

### ISSUE THREAD

**Issue by rsim** [emancu/toml-rb#59]
The following example gives parse exception

```ruby
>> TOML.parse "array = [\n  1,\n  # 2,\n  3,\n]"
TOML::ParseError: Failed to parse input on line 4 at offset 2
  3,

  ^
```

but if the indentation leading spaces are removed then there is no parse error

```ruby
>> TOML.parse "array = [\n1,\n# 2,\n3,\n]"
=> {"array"=>[1, 3]}
```

This is a common example that indentation spaces are used for multi-line arrays and if you want to comment out some value from the array then you have indentation spaces before comment as well.

**Comment by emancu** [comment]
Thanks for open a ticket. I'll take care next week.
