### ISSUE TITLE
Namespace conflict with require 'toml'

### ISSUE THREAD

**Issue by alvaromorales** [emancu/toml-rb#77]
I switched to `toml-rb` after having issues with [`toml`](https://rubygems.org/gems/toml). I've been very happy -- this library is more stable and actively developed :-)

If I install both `toml` and `toml-rb`, I get a namespace conflict. Both gems are included using `require 'toml'`, and have their modules under the `TOML` namespace. 

`toml` has been downloaded many times according to rubygems.org, so this might be a real issue.

How about `require 'toml-rb'` to avoid the namespace conflict?

**Comment by emancu** [comment]
Hi @alvaromorales ! Thanks for choosing `toml-rb`.

There is no way to change it and keep backwards compatibility.

Honestly I think it is not an issue. When you choose a gem to parse a TOML document, there is no need to pollute your environment with many different gems installed.

Sorry about that :/
