### ISSUE TITLE
Writing TOML with empty subsection not possible

### ISSUE THREAD

**Issue by fishnix** [emancu/toml-rb#80]
Hi! I'm trying to write TOML like this:

```toml
[plugins]
[[plugins.cpu]]
foo = "bar"
baz = 1234
[[plugins.disk]]
[[plugins.io]]
```

to configure [telegraf](https://github.com/influxdb/telegraf/blob/master/etc/telegraf.conf)

I would expect to be able to use something like:

```ruby
hash = {
  'plugins' => {
    'cpu' => {
      'foo' => 'bar',
      'baz' => 1234
    },
    'disk' => {},
    'io' => {}
  }
}

TOML.dump(hash)
```

but that gives me

`"[plugins.cpu]\nbaz = 1234\nfoo = \"bar\"\n"`

Any way to accomplish this?  Thanks!

**Comment by emancu** [comment]
Hmmm interesting.
Let me take a look on the specs and if I can do something about and I will
ping you back

On Tuesday, 22 December 2015, E Camden Fisher <notifications@github.com>
wrote:

> Hi! I'm trying to write TOML like this:
>
> [plugins]
> [[plugins.cpu]]foo = "bar"baz = 1234
> [[plugins.disk]]
> [[plugins.io]]
>
> to configure telegraf
> <https://github.com/influxdb/telegraf/blob/master/etc/telegraf.conf>
>
> I would expect to be able to use something like:
>
> hash = {
>   'plugins' => {
>     'cpu' => {
>       'foo' => 'bar',
>       'baz' => 1234
>     },
>     'disk' => {},
>     'io' => {}
>   }
> }
> TOML.dump(hash)
>
> but that gives me
>
> "[plugins.cpu]\nbaz = 1234\nfoo = \"bar\"\n"
>
> Any way to accomplish this? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emancu/toml-rb/issues/80>.
>


-- 
Emiliano Mancuso <http://about.me/emancu>

**Comment by emancu** [comment]
The following code:
```toml
[plugins]
[plugins.cpu]
foo = 'bar'
baz = 1234
[plugins.disk]
[plugins.io]
```

Produces:
```ruby
{
  "plugins" => {
    "cpu" => {
      "foo" => "bar",
      "baz" => 1234
    },
    "disk" => {},
    "io" => {}
  }
}
```

Which is actually what you want. But Thanks to you, I found a weird behaviour on the `dumper`. I need to take a look and see if it can be fixed or it is intentional.

Thanks!

**Comment by emancu** [comment]
cc @fishnix

**Comment by fishnix** [comment]
Thanks @emancu ! :+1:
