### ISSUE TITLE
TOML::ParseError

### ISSUE THREAD

**Issue by AxelAtS** [emancu/toml-rb#89]
This file content throws " **Failed to parse input on line 2 at offset 9 (TOML::ParseError)**" (but shouldn't, AFAIK):

**x = """\"Hello
World\""""**

Loaded with:

**TOML.load_file( path)**

Seems to be due to the last  **\"**.

Using:
* toml-rb-0.3.12
* ruby 1.9.3p327 (2012-11-10) [i386-mingw32]

Thank you for toml-rb!
Axel

**Comment by emancu** [comment]
@AxelAtS exactly, something weird is happening with the last `"`.
I will take a look this weekend.
In the meantime, I can suggest you to use single quotes for this scenario

```toml
x = '''"Hello
World"'''
```

Or use a more readable format

```toml
x = """
"Hello
World"
"""
```
