### ISSUE TITLE
Parsing Array of Tables containing Tables fails

### ISSUE THREAD

**Issue by AxelAtS** [emancu/toml-rb#91]
This:

```
toml = <<-HERE
  [[a]]
    [a.b]
    c = 'd'
  [[a]]
    [a.b]
    c = 'd'
HERE

TOML.parse( toml)

```

throws error:

```
keygroup.rb:22:in `ensure_key_not_defined': Key "a.b" is defined more than once (TOML::ValueOverwriteError)
```

but should return:

```
{"a"=>[{"b"=>{"c"=>"d"}}, {"b"=>{"c"=>"d"}}]}
```

Maybe I'm wrong...

Kind regards,
Axel

**Comment by emancu** [comment]
I'm going on vacations so I will take of this issue as soon as I can.

After releasing a fix for this one, I will push a new verision.
Thanks @AxelAtS for reporting this bugs and using the gem :)
