### ISSUE TITLE
namespace conflicts with `toml` gem

### ISSUE THREAD

**Issue by kplimack** [emancu/toml-rb#99]
I have pieces that require the `toml` gem, and some pieces that require `toml-rb`, except toml-rb is colliding with the other namespace and I cannot require each unambiguously.

**Comment by emancu** [comment]
@kplimack sad to hear that =( 

Changing the namespace will breaks the backwards compatibility so I would like to avoid doing that, but I see the problem and I want to provide a solution.

Could you tell me in which cases you require `toml` instead of `toml-rb` and why?

**Comment by kplimack** [comment]
InSpec (by Chef) uses `toml`
but some of the code im running with chef requires `toml-rb`.
so when I require ‘toml’, im at the will of the gem loader as to which I
get, which is non-deterministic.

thank for your help!

On April 11, 2017 at 5:42:07 PM, Mancuso Emiliano (notifications@github.com)
wrote:

@kplimack <https://github.com/kplimack> sad to hear that =(

Changing the namespace will breaks the backwards compatibility so I would
like to avoid doing that, but I see the problem and I want to provide a
solution.

Could you tell me in which cases you require toml instead of toml-rb and
why?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/emancu/toml-rb/issues/99#issuecomment-293431410>, or mute
the thread

**Comment by bdangit** [comment]
I suspect the original committer is having trouble with this conflict as well: https://github.com/bdangit/chef-influxdb/pull/143 . It would be good to have a proper namespace for this.

**Comment by kplimack** [comment]
Toml is a requirement of other components (inspec), so its not that simple.


On April 13, 2017 at 8:34:04 AM, Alaa Qutaish (notifications@github.com)
wrote:

This helped until we have different namespace chef_gem 'toml' { action
:remove }

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/emancu/toml-rb/issues/99#issuecomment-293913075>, or mute
the thread

**Comment by emancu** [comment]
Ok I'm open to receive PRs with a rename to `TomlRB.
Otherwise I will work on this renaming probably this weekend or the next one.

Thanks for reporting this!

**Comment by fortman** [comment]
👍 
Have same naming conflict issues.  inspec uses toml gem.  Multiple 3rd party Chef cookbooks we use require the toml-rb gem.  Our Chef runs were working fine, then we tried to use inspec for auditing and everything blew up :(

**Comment by fortman** [comment]
I downloaded the code and did the rename from TOML -> TomlRB as @emancu suggested.   Here is the output or the rake test command.

:>rake
workspace/toml-rb/test/grammar_test.rb:120: warning: Float 1e4000000 out of range
workspace/toml-rb/test/toml_examples.rb:83: warning: Float 1e1000 out of range
Run options: --seed 25350

# Running:

....<main>: warning: Float 1e1000 out of range
...........................<main>: warning: Float +1e4000000 out of range
........

Finished in 0.153232s, 254.5155 runs/s, 1318.2597 assertions/s.
39 runs, 202 assertions, 0 failures, 0 errors, 0 skips
workspace/toml-rb (module_conflict_rename)

I'm not sure if that constitutes a successful run, but if so, I can clone to my github area for a PR.

Also old school sed for the win.  sed 's/TOML/TomlRB/g' seems to have worked, but I can't say I've done testing other than the rake command.
